/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui.manager;

import java.awt.Image;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionListener;
import poly.cafe.dao.ShopDAO;
import poly.cafe.dao.TotalRevenueDAO;
import poly.cafe.dao.UserDAO;
import poly.cafe.dao.impl.ShopDAOImpl;
import poly.cafe.dao.impl.TotalRevenueDAOImpl;
import poly.cafe.dao.impl.UserDAOImpl;
import poly.cafe.entity.RevenueReportItem;
import poly.cafe.entity.Shop;
import poly.cafe.entity.User;
import poly.cafe.ui.manager.BranchRevenueController;
import poly.cafe.ui.manager.HomepageBranchManagerJFrame;
import poly.cafe.util.XDate;
import poly.cafe.util.XDialog;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author dthie
 */
public class BranchRevenueManagerJDialog extends javax.swing.JDialog implements BranchRevenueController {
    private final ShopDAO shopDAO;
    private final TotalRevenueDAO totalRevenueDAO; // Đã đổi tên
    private final UserDAO userDAO;
    private DefaultTableModel tblBranchModel;
    private DefaultTableModel tblRevenueModel;

    /**
     * Creates new form HomePage
     */
    public BranchRevenueManagerJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.shopDAO = new ShopDAOImpl();
        this.totalRevenueDAO = new TotalRevenueDAOImpl(); // Đã đổi tên
        this.userDAO = new UserDAOImpl();
        initComponents();
        initHeaderIcon(jLabel3);
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRevenue = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBranch = new javax.swing.JTable();
        lblBranchName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblManagerName = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        txtBegin = new javax.swing.JTextField();
        txtEnd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnFilter = new javax.swing.JButton();
        cboTimeRanges = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý doanh thu các chi nhánh");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(245, 236, 213));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Quản lý:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Địa chỉ:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Doanh thu:");

        tblRevenue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblRevenue.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Loại đồ uống", "Tên đồ uống", "Đã bán", "Doanh thu"
                }) {
            Class[] types = new Class[] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tblRevenue.setGridColor(new java.awt.Color(51, 0, 51));
        tblRevenue.setShowGrid(false);
        jScrollPane1.setViewportView(tblRevenue);

        btnExit.setBackground(new java.awt.Color(122, 92, 62));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Back");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tên chi nhánh:");

        tblBranch.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã chi nhánh", "Tên chi nhánh", "Địa chỉ"
                }));
        jScrollPane2.setViewportView(tblBranch);

        lblBranchName.setText("jLabel3");

        lblAddress.setText("jLabel3");
        lblAddress.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblManagerName.setText("jLabel5");

        lblTotalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalRevenue.setForeground(new java.awt.Color(122, 92, 62));
        lblTotalRevenue.setText("jLabel8");

        jLabel9.setText("Từ ngày:");

        jLabel10.setText("Đến ngày:");

        btnFilter.setText("Lọc");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        cboTimeRanges.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Hôm nay", "Tuần này", "Tháng này", "Quý này", "Năm nay" }));
        cboTimeRanges.setSelectedIndex(4);
        cboTimeRanges.setToolTipText("");
        cboTimeRanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTimeRangesActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 0, 51));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HighBUG");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                86, Short.MAX_VALUE)
                                                                        .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel7,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addGap(6, 6, 6)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblBranchName,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(lblManagerName,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(lblTotalRevenue,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jLabel1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblAddress,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))))
                                        .addComponent(btnExit)
                                        .addGroup(jPanel5Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout
                                                        .createSequentialGroup()
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cboTimeRanges,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 668,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                134, Short.MAX_VALUE))
                                                .addGap(15, 15, 15)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel10)
                                                        .addComponent(btnFilter)
                                                        .addComponent(cboTimeRanges,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addComponent(btnExit))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(lblBranchName))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(lblManagerName))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(lblAddress))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(lblTotalRevenue))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(15, 15, 15)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void init() {
        this.setLocationRelativeTo(null);

        tblBranchModel = (DefaultTableModel) tblBranch.getModel();
        tblRevenueModel = (DefaultTableModel) tblRevenue.getModel();

        // Set up custom renderer for revenue column
        NumberFormat currencyFormatter = new java.text.DecimalFormat("#,##0 VNĐ");
        tblRevenue.getColumnModel().getColumn(3).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (value instanceof Number) {
                    setText(currencyFormatter.format(value));
                } else {
                    setText(value != null ? value.toString() : "");
                }
                return this;
            }
        });

        // Set up table selection listener
        tblBranch.getSelectionModel().addListSelectionListener((ListSelectionListener) (e) -> {
            if (!e.getValueIsAdjusting()) {
                updateSummaryInfo();
                fillRevenueReport();
            }
        });

        cboTimeRanges.setSelectedIndex(4); // Mặc định chọn "Năm nay"
        selectPredefinedTimeRange();

        fillBranchTable();

        if (tblBranch.getRowCount() > 0) {
            tblBranch.setRowSelectionInterval(0, 0);
            updateSummaryInfo();
            // Không gọi fillRevenueReport() ở đây, để listener xử lý
        } else {
            clearSummaryInfo();
        }
    }

    @Override
    public void fillBranchTable() {
        tblBranchModel.setRowCount(0);
        try {
            List<Shop> shops = shopDAO.findAll();
            for (Shop shop : shops) {
                tblBranchModel.addRow(new Object[] { shop.getId(), shop.getShopName(), shop.getAddress() });
            }
        } catch (Exception e) {
            XDialog.alert("Lỗi tải danh sách chi nhánh!");
            e.printStackTrace();
        }
    }

    private void clearSummaryInfo() {
        lblBranchName.setText("Chưa chọn chi nhánh");
        lblAddress.setText("...");
        lblManagerName.setText("...");
        lblTotalRevenue.setText("0 VNĐ");
        tblRevenueModel.setRowCount(0);
    }

    @Override
    public void fillRevenueReport() {
        System.out.println("=== fillRevenueReport() called ===");
        tblRevenueModel.setRowCount(0);
        int selectedRow = tblBranch.getSelectedRow();
        if (selectedRow < 0) {
            System.out.println("No branch selected");
            lblTotalRevenue.setText("0 VNĐ");
            return;
        }

        String shopId = (String) tblBranch.getValueAt(selectedRow, 0);
        System.out.println("Selected ShopId: " + shopId);

        Date beginDate = XDate.parse(txtBegin.getText(), "dd-MM-yyyy");
        Date endDate = XDate.parse(txtEnd.getText(), "dd-MM-yyyy");

        System.out.println("Begin date text: " + txtBegin.getText() + " -> parsed: " + beginDate);
        System.out.println("End date text: " + txtEnd.getText() + " -> parsed: " + endDate);

        if (beginDate == null || endDate == null) {
            System.out.println("Invalid date format");
            lblTotalRevenue.setText("0 VNĐ");
            return;
        }
        // Normalize date range to cover full days: [00:00:00.000, 23:59:59.999]
        beginDate = atStartOfDay(beginDate);
        endDate = atEndOfDay(endDate);

        try {
            // Sử dụng DAO đã đổi tên
            List<RevenueReportItem> reportItems = totalRevenueDAO.getRevenueByShopAndDateRange(shopId, beginDate,
                    endDate);
            System.out.println("Report items returned: " + reportItems.size());

            double totalRevenue = 0;

            // Tạo formatter tùy chỉnh để hiển thị VNĐ
            NumberFormat currencyFormatter = new java.text.DecimalFormat("#,##0 VNĐ");

            for (RevenueReportItem item : reportItems) {
                // Ensure the values are not null and handle them properly
                String categoryName = item.getCategoryName() != null ? item.getCategoryName() : "";
                String drinkName = item.getDrinkName() != null ? item.getDrinkName() : "";
                Integer quantitySold = item.getQuantitySold();

                // Check if totalRevenue is valid
                double revenue = item.getTotalRevenue();
                if (Double.isNaN(revenue) || Double.isInfinite(revenue)) {
                    revenue = 0.0;
                }

                System.out.println(
                        "Adding row: " + categoryName + ", " + drinkName + ", " + quantitySold + ", " + revenue);

                tblRevenueModel.addRow(new Object[] {
                        categoryName,
                        drinkName,
                        quantitySold,
                        revenue
                });
                totalRevenue += revenue;
            }

            System.out.println("Total revenue: " + totalRevenue);
            lblTotalRevenue.setText(currencyFormatter.format(totalRevenue));

        } catch (Exception e) {
            System.err.println("Lỗi tải báo cáo doanh thu: " + e.getMessage());
            e.printStackTrace();
            lblTotalRevenue.setText("0 VNĐ");
        }
    }

    @Override
    public void updateSummaryInfo() {
        int selectedRow = tblBranch.getSelectedRow();
        if (selectedRow < 0) {
            clearSummaryInfo();
            return;
        }

        String shopId = (String) tblBranch.getValueAt(selectedRow, 0);
        Shop shop = shopDAO.findById(shopId);

        if (shop != null) {
            // Cho phép xuống dòng bằng HTML để auto-wrap
            lblBranchName.setText("<html>" + escapeHtml(shop.getShopName()) + "</html>");
            lblAddress.setText("<html>" + escapeHtml(shop.getAddress()) + "</html>");

            // Lấy thông tin người quản lý để hiển thị FullName
            String managerUsername = shop.getManagerUsername();
            if (managerUsername != null && !managerUsername.isEmpty()) {
                try {
                    User manager = userDAO.findById(managerUsername);
                    if (manager != null) {
                        lblManagerName.setText(manager.getFullname());
                    } else {
                        lblManagerName.setText("Không tìm thấy thông tin quản lý");
                    }
                } catch (Exception e) {
                    lblManagerName.setText("Lỗi tải thông tin quản lý");
                }
            } else {
                lblManagerName.setText("Chưa có quản lý");
            }
        }
    }

    @Override
    public void selectPredefinedTimeRange() {
        int selectedIndex = cboTimeRanges.getSelectedIndex();
        Date now = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(now);

        Date beginDate;
        Date endDate = now;

        switch (selectedIndex) {
            case 0: // Hôm nay
                beginDate = now;
                break;
            case 1: // Tuần này
                cal.set(Calendar.DAY_OF_WEEK, cal.getFirstDayOfWeek());
                beginDate = cal.getTime();
                break;
            case 2: // Tháng này
                cal.set(Calendar.DAY_OF_MONTH, 1);
                beginDate = cal.getTime();
                break;
            case 3: // Quý này
                int month = cal.get(Calendar.MONTH);
                int quarter = month / 3;
                cal.set(Calendar.MONTH, quarter * 3);
                cal.set(Calendar.DAY_OF_MONTH, 1);
                beginDate = cal.getTime();
                break;
            case 4: // Năm nay
            default:
                cal.set(Calendar.DAY_OF_YEAR, 1);
                beginDate = cal.getTime();
                break;
        }

        txtBegin.setText(XDate.format(beginDate, "dd-MM-yyyy"));
        txtEnd.setText(XDate.format(endDate, "dd-MM-yyyy"));

        // Gọi fillRevenueReport() nếu có chi nhánh được chọn
        if (tblBranch.getSelectedRow() >= 0) {
            fillRevenueReport();
        }
    }

    // Escape ký tự đặc biệt khi dùng HTML trong JLabel
    private static String escapeHtml(String s) {
        if (s == null)
            return "";
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

    // Gắn icon coffee cho tiêu đề
    private void initHeaderIcon(javax.swing.JLabel label) {
        try {
            ImageIcon icon = poly.cafe.util.IconUtils.loadCoffeeIcon(24, 24);
            if (icon != null) {
                label.setIcon(icon);
                label.setHorizontalTextPosition(SwingConstants.RIGHT);
                label.setVerticalTextPosition(SwingConstants.CENTER);
                label.setIconTextGap(8);
            }
        } catch (Exception ignore) {
        }
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
        // Đóng dialog hiện tại và mở HomepageBranchManagerJFrame
        this.dispose();
        HomepageBranchManagerJFrame homepage = new HomepageBranchManagerJFrame();
        homepage.setVisible(true);
    }// GEN-LAST:event_btnExitActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFilterActionPerformed
        // Lọc theo khoảng thời gian đã nhập
        if (tblBranch.getSelectedRow() >= 0) {
            fillRevenueReport();
        } else {
            XDialog.alert("Vui lòng chọn một chi nhánh để xem báo cáo doanh thu!");
        }
    }// GEN-LAST:event_btnFilterActionPerformed

    private void cboTimeRangesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cboTimeRangesActionPerformed
        // Chọn khoảng thời gian định sẵn
        selectPredefinedTimeRange();
    }// GEN-LAST:event_cboTimeRangesActionPerformed

    // Helpers to normalize date range to full day
    private Date atStartOfDay(Date date) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        return cal.getTime();
    }

    private Date atEndOfDay(Date date) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.set(Calendar.HOUR_OF_DAY, 23);
        cal.set(Calendar.MINUTE, 59);
        cal.set(Calendar.SECOND, 59);
        cal.set(Calendar.MILLISECOND, 999);
        return cal.getTime();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchRevenueManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchRevenueManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchRevenueManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchRevenueManagerJDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BranchRevenueManagerJDialog dialog = new BranchRevenueManagerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JComboBox<String> cboTimeRanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBranchName;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JTable tblBranch;
    private javax.swing.JTable tblRevenue;
    private javax.swing.JTextField txtBegin;
    private javax.swing.JTextField txtEnd;
    // End of variables declaration//GEN-END:variables

}
