/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui.manager;

import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Zikar
 */
public class HomepageBranchManagerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomepageBranchManagerJFrame
     */
    public HomepageBranchManagerJFrame() {
        initComponents();
        initFrame();
        addChartsToPanel();
    }

    private void initFrame() {
        // Đặt giữa màn hình
        this.setLocationRelativeTo(null);

        // Đảm bảo hiển thị lên trên khi mở ra, sau đó trả về bình thường
        this.setAlwaysOnTop(true);
        this.toFront();
        this.requestFocus();
        SwingUtilities.invokeLater(() -> this.setAlwaysOnTop(false));

        // Gán logo giống PolyCafe
        try {
            String fallbackCoffeeLogo = "/poly/cafe/images/icons/coffee.png";
            java.net.URL logoUrl = getClass().getResource(fallbackCoffeeLogo);
            if (logoUrl != null) {
                ImageIcon logoIcon = new ImageIcon(logoUrl);
                java.awt.Image scaledLogo = logoIcon.getImage().getScaledInstance(24, 24,
                        java.awt.Image.SCALE_SMOOTH);
                lbLogoName.setIcon(new ImageIcon(scaledLogo));
                lbLogoName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                lbLogoName.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
                lbLogoName.setIconTextGap(10);
            }
        } catch (Exception ignore) {
        }
    }

    // Demo thêm chart (pie + bar) lên jPanel5 sử dụng JFreeChart
    private void addChartsToPanel() {
        try {
            // Pie chart dataset
            org.jfree.data.general.DefaultPieDataset<String> pieDataset = new org.jfree.data.general.DefaultPieDataset<>();
            pieDataset.setValue("CN1", 45);
            pieDataset.setValue("CN2", 25);
            pieDataset.setValue("CN3", 30);

            org.jfree.chart.JFreeChart pieChart = org.jfree.chart.ChartFactory.createPieChart(
                    "Tỉ trọng doanh thu", pieDataset, true, true, false);
            org.jfree.chart.ChartPanel piePanel = new org.jfree.chart.ChartPanel(pieChart);
            piePanel.setPreferredSize(new java.awt.Dimension(260, 180));

            // Bar chart dataset
            org.jfree.data.category.DefaultCategoryDataset barDataset = new org.jfree.data.category.DefaultCategoryDataset();
            barDataset.addValue(120, "Doanh thu", "CN1");
            barDataset.addValue(80, "Doanh thu", "CN2");
            barDataset.addValue(95, "Doanh thu", "CN3");

            org.jfree.chart.JFreeChart barChart = org.jfree.chart.ChartFactory.createBarChart(
                    "Doanh thu theo chi nhánh", "Chi nhánh", "Triệu VNĐ", barDataset);
            org.jfree.chart.ChartPanel barPanel = new org.jfree.chart.ChartPanel(barChart);
            barPanel.setPreferredSize(new java.awt.Dimension(260, 180));

            // Thêm vào jPanel5 (sử dụng GroupLayout hiện có: chèn đơn giản bằng
            // BorderLayout phụ)
            java.awt.Panel container = new java.awt.Panel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
            container.add(piePanel);
            container.add(barPanel);

            // Gắn container vào cuối jPanel5
            jPanel5.add(container, java.awt.BorderLayout.SOUTH);
            jPanel5.revalidate();
            jPanel5.repaint();
        } catch (Throwable t) {
            // Không chặn UI nếu thiếu lib; chỉ log nhẹ
            System.err.println("Không thể tạo chart: " + t.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnExit = new javax.swing.JButton();
        btnBranchManager = new javax.swing.JButton();
        btnEmployeeBranchManager = new javax.swing.JButton();
        btnCreateNewBranch = new javax.swing.JButton();
        btnCreateNewBranchManager = new javax.swing.JButton();
        lbLogoName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(245, 236, 213));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Trang chủ");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(184, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(209, 209, 209)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        btnExit.setBackground(new java.awt.Color(113, 92, 62));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("ĐĂNG XUẤT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnBranchManager.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBranchManager.setText("QUẢN LÝ CHI NHÁNH");
        btnBranchManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBranchManagerActionPerformed(evt);
            }
        });

        btnEmployeeBranchManager.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEmployeeBranchManager.setText("QUẢN LÝ NHÂN VIÊN");
        btnEmployeeBranchManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeBranchManagerActionPerformed(evt);
            }
        });

        btnCreateNewBranch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCreateNewBranch.setText("TẠO CHI NHÁNH MỚI");
        btnCreateNewBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewBranchActionPerformed(evt);
            }
        });

        btnCreateNewBranchManager.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCreateNewBranchManager.setText("TẠO QUẢN LÝ MỚI");
        btnCreateNewBranchManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewBranchManagerActionPerformed(evt);
            }
        });

        lbLogoName.setBackground(new java.awt.Color(255, 255, 255));
        lbLogoName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbLogoName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogoName.setText("HighBUG");
        lbLogoName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        lbLogoName.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbLogoName, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCreateNewBranchManager, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCreateNewBranch, javax.swing.GroupLayout.DEFAULT_SIZE, 183,
                                                Short.MAX_VALUE)
                                        .addComponent(btnEmployeeBranchManager, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBranchManager, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbLogoName, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnBranchManager, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEmployeeBranchManager, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreateNewBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreateNewBranchManager, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167,
                                        Short.MAX_VALUE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
        if (poly.cafe.util.XDialog.confirm("Bạn muốn đăng xuất?")) {
            try {
                this.dispose();
            } finally {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    poly.cafe.ui.LoginJDialog login = new poly.cafe.ui.LoginJDialog(null, true);
                    login.setLocationRelativeTo(null);
                    login.setVisible(true);
                });
            }
        }
    }// GEN-LAST:event_btnExitActionPerformed

    private void btnBranchManagerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBranchManagerActionPerformed
        BranchRevenueManagerJDialog dialog = new BranchRevenueManagerJDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnBranchManagerActionPerformed

    private void btnEmployeeBranchManagerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEmployeeBranchManagerActionPerformed
        EmployeeBranchManagerJDialog dialog = new EmployeeBranchManagerJDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnEmployeeBranchManagerActionPerformed

    private void btnCreateNewBranchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateNewBranchActionPerformed
        NewBranchManagerJDialog dialog = new NewBranchManagerJDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnCreateNewBranchActionPerformed

    private void btnCreateNewBranchManagerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateNewBranchManagerActionPerformed
        NewEmployeeBranchManagerJDialog dialog = new NewEmployeeBranchManagerJDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }// GEN-LAST:event_btnCreateNewBranchManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomepageBranchManagerJFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomepageBranchManagerJFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomepageBranchManagerJFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomepageBranchManagerJFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomepageBranchManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBranchManager;
    private javax.swing.JButton btnCreateNewBranch;
    private javax.swing.JButton btnCreateNewBranchManager;
    private javax.swing.JButton btnEmployeeBranchManager;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbLogoName;
    // End of variables declaration//GEN-END:variables
}
